/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#340080",
        "primary-fixed": "#e9ddff",
        "on-primary-fixed": "#23005c",
        "on-secondary-fixed-variant": "#2f2ebe",
        "primary-container": "#a078ff",
        "tertiary-fixed": "#c4e7ff",
        "inverse-on-surface": "#2f3036",
        "secondary-fixed": "#e1e0ff",
        "on-tertiary-fixed-variant": "#004c69",
        "error": "#ffb4ab",
        "surface-container-highest": "#34343a",
        "on-surface-variant": "#cbc3d7",
        "inverse-primary": "#6d3bd7",
        "secondary-container": "#3131c0",
        "on-secondary": "#1000a9",
        "surface-container-lowest": "#0d0e13",
        "surface-dim": "#121318",
        "surface": "#121318",
        "surface-container": "#1e1f25",
        "surface-bright": "#38393f",
        "on-primary": "#3c0091",
        "on-surface": "#e3e1e9",
        "tertiary-container": "#009bd1",
        "error-container": "#93000a",
        "tertiary-fixed-dim": "#7bd0ff",
        "surface-container-low": "#1a1b21",
        "surface-container-high": "#292a2f",
        "tertiary": "#7bd0ff",
        "outline": "#958ea0",
        "secondary": "#c0c1ff",
        "surface-tint": "#d0bcff",
        "on-secondary-fixed": "#07006c",
        "on-error": "#690005",
        "on-tertiary": "#00354a",
        "on-background": "#e3e1e9",
        "secondary-fixed-dim": "#c0c1ff",
        "background": "#121318",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e3e1e9",
        "on-secondary-container": "#b0b2ff",
        "primary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed": "#001e2c",
        "primary": "#d0bcff",
        "on-tertiary-container": "#002d40",
        "outline-variant": "#494454",
        "on-primary-fixed-variant": "#5516be",
        "surface-variant": "#34343a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin": "3rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "headline-lg-mobile": [ "Plus Jakarta Sans", "sans-serif" ],
        "label-sm": [ "Space Grotesk", "sans-serif" ],
        "headline-display": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-lg": [ "Plus Jakarta Sans", "sans-serif" ],
        "body-lg": [ "Inter", "sans-serif" ],
        "headline-display-mobile": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-sm": [ "Plus Jakarta Sans", "sans-serif" ],
        "body-md": [ "Inter", "sans-serif" ],
        "headline-md": [ "Plus Jakarta Sans", "sans-serif" ],
        "body-sm": [ "Inter", "sans-serif" ],
        "label-lg": [ "Space Grotesk", "sans-serif" ],
        "label-md": [ "Space Grotesk", "sans-serif" ]
      },
      fontSize: {
        "headline-lg-mobile": [ "28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" } ],
        "label-sm": [ "10px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" } ],
        "headline-display": [ "56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" } ],
        "headline-lg": [ "40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "600" } ],
        "body-lg": [ "18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" } ],
        "headline-display-mobile": [ "36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" } ],
        "headline-sm": [ "20px", { lineHeight: "28px", letterSpacing: "-0.015em", fontWeight: "600" } ],
        "body-md": [ "15px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "400" } ],
        "headline-md": [ "28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" } ],
        "body-sm": [ "13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" } ],
        "label-lg": [ "14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "500" } ],
        "label-md": [ "12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" } ]
      }
    },
  },
  plugins: [],
}
